### ISSUE TITLE
Kosovo country

### ISSUE THREAD

**Issue by arturmaksimovic** [sokil/php-isocodes-db-i18n#26]
The country of Kosovo is missing

**Comment by sokil** [comment]
This library is using Debian's package https://salsa.debian.org/iso-codes-team/iso-codes that in turn made according to ISO 3166. Currently this iso does not contain codes related to Kosovo as independent country. 

I understand how sensitive this issue is, and know how many countries already recognized it, but this library is just a wrapper aroung other Debians library, and that library is just representation of ISO, so i cant make any political decisions here.

I may only advise you to extend this library for your needs.
